************* Module conftest
example_code/cognito/test/conftest.py:8:0: W0401: Wildcard import test_tools.fixtures.common (wildcard-import)
example_code/cognito/test/conftest.py:9:0: C0411: standard import "import random" should be placed before "from test_tools.fixtures.common import *" (wrong-import-order)
example_code/cognito/test/conftest.py:10:0: C0411: standard import "import sys" should be placed before "from test_tools.fixtures.common import *" (wrong-import-order)
example_code/cognito/test/conftest.py:9:0: W0611: Unused import random (unused-import)
************* Module test_cognito_idp_actions
example_code/cognito/test/test_cognito_idp_actions.py:152:0: R0914: Too many local variables (18/15) (too-many-locals)
example_code/cognito/test/test_cognito_idp_actions.py:220:0: R0914: Too many local variables (16/15) (too-many-locals)
example_code/cognito/test/test_cognito_idp_actions.py:258:0: R0914: Too many local variables (19/15) (too-many-locals)
example_code/cognito/test/test_cognito_idp_actions.py:313:0: R0914: Too many local variables (19/15) (too-many-locals)
************* Module test_scenario_signup_user_with_mfa
example_code/cognito/test/test_scenario_signup_user_with_mfa.py:36:0: R0914: Too many local variables (31/15) (too-many-locals)
example_code/cognito/test/test_scenario_signup_user_with_mfa.py:36:0: R0915: Too many statements (55/50) (too-many-statements)
example_code/cognito/test/test_scenario_signup_user_with_mfa.py:1:0: R0801: Similar lines in 2 files
==test_cognito_idp_actions:[342:368]
==test_scenario_signup_user_with_mfa:[160:187]
        runner.add(
            cognito_idp_stubber.stub_initiate_auth,
            client_id,
            "USER_PASSWORD_AUTH",
            user_name,
            password,
            device_key,
            "DEVICE_SRP_AUTH",
        )
        runner.add(
            cognito_idp_stubber.stub_respond_to_auth_challenge,
            client_id,
            "DEVICE_SRP_AUTH",
            aws_srp.AWSSRP.get_auth_params("s"),
            "DEVICE_PASSWORD_VERIFIER",
            {},
        )
        runner.add(
            cognito_idp_stubber.stub_respond_to_auth_challenge,
            client_id,
            "DEVICE_PASSWORD_VERIFIER",
            aws_srp.AWSSRP.process_challenge("s", True, True),
            "",
            access_token=access_token,
        )
    if error_code is None: (duplicate-code)
example_code/cognito/test/test_scenario_signup_user_with_mfa.py:1:0: R0801: Similar lines in 2 files
==test_cognito_idp_actions:[326:341]
==test_scenario_signup_user_with_mfa:[61:76]
    aws_srp.AWSSRP = MagicMock
    aws_srp.AWSSRP.get_auth_params = lambda s: {
        "USERNAME": user_name,
        "SRP_A": "test-srp-a",
        "DEVICE_KEY": device_key,
    }
    tstamp = str(datetime.utcnow())
    aws_srp.AWSSRP.process_challenge = lambda s, x, r: {
        "TIMESTAMP": tstamp,
        "USERNAME": user_name,
        "PASSWORD_CLAIM_SECRET_BLOCK": "test-secret-block",
        "PASSWORD_CLAIM_SIGNATURE": "test-signature",
        "DEVICE_KEY": device_key,
    }
 (duplicate-code)
example_code/cognito/test/test_scenario_signup_user_with_mfa.py:1:0: R0801: Similar lines in 2 files
==test_cognito_idp_actions:[168:175]
==test_scenario_signup_user_with_mfa:[114:121]
        runner.add(
            cognito_idp_stubber.stub_admin_initiate_auth,
            user_pool_id,
            client_id,
            "ADMIN_USER_PASSWORD_AUTH",
            user_name,
            password, (duplicate-code)
example_code/cognito/test/test_scenario_signup_user_with_mfa.py:1:0: R0801: Similar lines in 2 files
==test_cognito_idp_actions:[270:275]
==test_scenario_signup_user_with_mfa:[56:61]
    aws_srp = MagicMock()
    aws_srp.hash_sha256 = lambda x: device_and_pw_hash
    pad_hex_results = [salt, verifier]
    aws_srp.pad_hex = lambda x: pad_hex_results.pop(0)
    aws_srp.hex_to_long = lambda x: 12345467890 (duplicate-code)

------------------------------------------------------------------
Your code has been rated at 9.41/10 (previous run: 9.41/10, +0.00)

